version: '3.8'

services:
  gpt-augment:
    image: yanickpfischer/ukrainebias-gpt-augment:latest
    container_name: gpt-augment
    depends_on:
      - mongo
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGO_URI: ${MONGO_URI}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      NITTER_INSTANCE: ${NITTER_INSTANCE}
      MODEL_PATH: ${MODEL_PATH}
      GPT_BATCH_SIZE: ${GPT_BATCH_SIZE}
      GPT_SLEEP_TIME: ${GPT_SLEEP_TIME}

  gpt-filter-sentiment:
    image: yanickpfischer/ukrainebias-gpt-filter-sentiment:latest
    container_name: gpt-filter-sentiment
    depends_on:
      - mongo
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGO_URI: ${MONGO_URI}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      NITTER_INSTANCE: ${NITTER_INSTANCE}
      MODEL_PATH: ${MODEL_PATH}
      GPT_BATCH_SIZE: ${GPT_BATCH_SIZE}
      GPT_SLEEP_TIME: ${GPT_SLEEP_TIME}

  model-trainer:
    image: yanickpfischer/ukrainebias-model-trainer:latest
    container_name: model-trainer
    depends_on:
      - mongo
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGO_URI: ${MONGO_URI}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      NITTER_INSTANCE: ${NITTER_INSTANCE}
      MODEL_PATH: ${MODEL_PATH}
      GPT_BATCH_SIZE: ${GPT_BATCH_SIZE}
      GPT_SLEEP_TIME: ${GPT_SLEEP_TIME}

  twitter-scraper:
    image: yanickpfischer/ukrainebias-twitter-scraper:latest
    container_name: twitter-scraper
    depends_on:
      - mongo
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGO_URI: ${MONGO_URI}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      NITTER_INSTANCE: ${NITTER_INSTANCE}

  app:
    image: yanickpfischer/ukrainebias-app:latest
    container_name: app
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGO_URI: ${MONGO_URI}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      NITTER_INSTANCE: ${NITTER_INSTANCE}
      MODEL_PATH: ${MODEL_PATH}
      GPT_BATCH_SIZE: ${GPT_BATCH_SIZE}
      GPT_SLEEP_TIME: ${GPT_SLEEP_TIME}

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"