# Start mit leichtgewichtigem Python-Image
FROM python:3-slim

# Optimierungen für Container-Umgebung
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Arbeitsverzeichnis setzen
WORKDIR /backend/twitter-scraper

# Abhängigkeiten installieren
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Quellcode kopieren
COPY . .

# Non-root User für Sicherheit
RUN adduser --disabled-password --gecos "" appuser && chown -R appuser .
USER appuser

# Startkommando
CMD ["python", "scrape_balanced_sample.py"]