# Base image
FROM python:3.11-slim

# Port für Gunicorn
EXPOSE 5000

# Keine .pyc-Dateien und besseres Logging
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Arbeitsverzeichnis setzen
WORKDIR /app

# Abhängigkeiten installieren
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# App-Code kopieren
COPY . .

# Non-root user für mehr Sicherheit
RUN adduser --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# Gunicorn als Production Server
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]