name: Deploy Docker Compose to Azure Web App

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Multi-Container App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure Login via Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy multi-container app to Azure using Compose
      run: |
        az webapp config container set \
          --name mdm-ukraineBias-app \
          --resource-group mdm-ukraineBias-rg \
          --multicontainer-config-type compose \
          --multicontainer-config-file docker-compose.yaml
