name: Deploy Docker Compose to Azure Web App

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Multi-Container App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure Login via Publish Profile
      uses: azure/webapps-deploy@v2
      with:
        app-name: mdm-ukraineBias-app
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: |
          yanickpfischer/ukrainebias-app:latest
          yanickpfischer/ukrainebias-twitter-scraper:latest
          yanickpfischer/ukrainebias-gpt-augment:latest
          yanickpfischer/ukrainebias-gpt-filter-sentiment:latest
          yanickpfischer/ukrainebias-model-trainer:latest
        configuration-file: docker-compose.yaml